### ISSUE TITLE
The first 'lock' of a list after meteor reset results in the list details clearing

### ISSUE THREAD

**Issue by domyen** [percolatestudio/mdg-todos#1]
Repro
1. Meteor reset
2. Join
3. Sign in
4. Lock the list
5. The list enters an unexpected state where the title & items disappear

![screenshot 2014-09-05 11 18 14](https://cloud.githubusercontent.com/assets/263385/4169609/07afa32a-3529-11e4-80af-944f9a5e77d4.png)

**Comment by domyen** [comment]
Note: Also occurs in mobile via the <select>

To see the real list you need to click on a new list and then click back to the old list.

**Comment by tmeasday** [comment]
Wow, good pick up. Note there's a slightly simple repro:
1. Logout
2. Login
3. Click private button.

**Comment by tmeasday** [comment]
I think this is an instance of https://github.com/EventedMind/iron-router/issues/754. It appears that 1.0.0 (currently in pre-release) fixes this. Can't get IR to run properly with Todos yet though. Will circle back in a day or two after ironing [:)] out some of these issues with Chris.

**Comment by tmeasday** [comment]
This appears fixed in IR 1.0.0-pre2.

**Comment by zol** [comment]
n.b I've seen this state happen to a list by adding a new item.

**Comment by stubailo** [comment]
Can we upgrade to IR 1.0.0-pre2 or above?

**Comment by tmeasday** [comment]
https://github.com/EventedMind/iron-router/issues/869

**Comment by tmeasday** [comment]
@stubailo IR 1.0.x isn't really ready enough to be rc-ed so I think it's better to figure a fix to IR 0.9.x. I'll try to get an RC with fix out ASAP.

**Comment by stubailo** [comment]
I was hoping to release a preview tonight - do you think the fix is easy?

**Comment by tmeasday** [comment]
Give me 20 minutes and I'll tell you more.

**Comment by tmeasday** [comment]
@stubailo I actually don't think @cmather has ever given me permission to publish rcs of IR. I believe @avital has permission though. OTOH I could just publish a fork.

**Comment by stubailo** [comment]
Why can't we just use the pre-release of IR? does it include this fix? We will need to upgrade to the new version of IR later anyway.

**Comment by stubailo** [comment]
If that's not a valid solution, publishing a fork is fine for now.

**Comment by tmeasday** [comment]
I have a fix -- double checking now.

I'm loathe to use IR1.0-pre because:
 a) the syntax of IR has changed in significant ways. Getting todos to work with it was non-trivial.
 b) it is still pretty buggy and I'm not 100% there aren't different bugs with using it with todos.
 c) I'm not at all sure about the release schedule so but I know it's unlikely to be out before this app.

**Comment by tmeasday** [comment]
Confirmed that the fix works with todos.

**Comment by stubailo** [comment]
OK do the fork

**Comment by tmeasday** [comment]
Arggh. For some reason I can't publish the package (to my own namespace). I'm getting a random `ENOENT, no such file or directory '/private/tmp/iron-router/.npm/package/node_modules'` error. 

I'll open a bug against core. 

@stubailo do you want to try publishing your own version? https://github.com/EventedMind/iron-router branch `0.9`.

**Comment by tmeasday** [comment]
(I checked out to `/tmp` as it had the same problem in my development dir).

**Comment by stubailo** [comment]
Published mine to sashko:router@0.9.4-rc0 - try it out!

**Comment by tmeasday** [comment]
Nice. Although I have @cmather here, he's going to publish it as 0.9.3.1.

**Comment by tmeasday** [comment]
P.S did we ever get a resolution to #28? Should I investigate further?

**Comment by stubailo** [comment]
OK awesome, post here when it's done! for #28, we'll just say there are a few Cordova bugs we are working on and that it's a preview.

**Comment by tmeasday** [comment]
Fixed.

**Comment by cmather** [comment]
rock and roll

**Comment by stubailo** [comment]
Awesome, going to test now

**Comment by stubailo** [comment]
I'm still getting the error - `meteor reset` `meteor` then join, then click lock button, and the list disappears.

**Comment by stubailo** [comment]
Oh never mind, not anymore. Had some weird state on my system.

**Comment by tmeasday** [comment]
You need to restart your meteor server after updating packages these days it seems :)

**Comment by zol** [comment]
lgtm.
